/*
 * This file was automatically generated by tecsgen.
 * Move and rename like below before editing,
 *   gen/tTCPCEPwrapper4_template.c => src/tTCPCEPwrapper4.c
 * to avoid to be overwritten by tecsgen.
 */
/* #[<PREAMBLE>]#
 * Don't edit the comments between #[<...>]# and #[</...>]#
 * These comment are used by tecsmerege when merging.
 *
 * attr access macro #_CAAM_#
 * myaddr           T_IN4_ADDR       VAR_myaddr
 * dstaddr          T_IN4_ADDR       VAR_dstaddr
 *
 * call port function #_TCPF_#
 * call port : cAPI  signature: sTCPCEPAPI context: task
 *   ER             cAPI_accept( intptr_t sREP4, uint16_t* dstport, TMO tmout );
 *   ER             cAPI_connect( const int8_t* myaddr, uint16_t myport, const int8_t* dstaddr, uint16_t dstport, int32_t addrlen, TMO tmout );
 *   ER_UINT        cAPI_send( const int8_t* data, int32_t len, TMO tmout );
 *   ER_UINT        cAPI_receive( int8_t* data, int32_t len, TMO tmout );
 *   ER             cAPI_cancel( FN fncd );
 *   ER             cAPI_close( TMO tmout );
*   ER             cAPI_shutdown( );
 *
 * #[</PREAMBLE>]# */

/* Put prototype declaration and/or variale definition here #_PAC_# */
#include "tTCPCEPwrapper4_tecsgen.h"

#ifndef E_OK
#define	E_OK	0		/* success */
#define	E_ID	(-18)	/* illegal ID */
#endif

/* entry port function #_TEPF_# */
/* #[<ENTRY_PORT>]# eAPI4
 * entry port: eAPI4
 * signature:  sTCPCEPAPI4
 * context:    task
 * #[</ENTRY_PORT>]# */

#define sREP4_des intptr_t //dynamic

/* #[<ENTRY_FUNC>]# eAPI4_accept
 * name:         eAPI4_accept
 * global_name:  tTCPCEPwrapper4_eAPI4_accept
 * oneway:       false
 * #[</ENTRY_FUNC>]# */
ER
eAPI4_accept(CELLIDX idx, Descriptor( sREP4 ) desc, T_IPV4EP* dstep4, TMO tmout)
{
	ER		ercd = E_OK;
	CELLCB	*p_cellcb;
	if (VALID_IDX(idx)) {
		p_cellcb = GET_CELLCB(idx);
	}
	else {
		return(E_ID);
	} /* end if VALID_IDX(idx) */

	/* Put statements here #_TEFB_# */
	uint16_t dstport;

	/* p_dstaddr = NULL もしくは tmout = TMO_NBLK ならエラー */
	if (dstep4 == NULL || tmout == TMO_NBLK)
	  return E_PAR;

	if((ercd = cAPI_accept(desc, &dstport, tmout )) == E_OK){
		dstep4->ipaddr = VAR_dstaddr;
		dstep4->portno = dstport;
	}

	return(ercd);
}

/* #[<ENTRY_FUNC>]# eAPI4_connect
 * name:         eAPI4_connect
 * global_name:  tTCPCEPwrapper4_eAPI4_connect
 * oneway:       false
 * #[</ENTRY_FUNC>]# */
ER
eAPI4_connect(CELLIDX idx, T_IN4_ADDR myaddr, uint16_t myport, T_IN4_ADDR dstaddr, uint16_t dstport, TMO tmout)
{
	ER		ercd = E_OK;
	CELLCB	*p_cellcb;
	if (VALID_IDX(idx)) {
		p_cellcb = GET_CELLCB(idx);
	}
	else {
		return(E_ID);
	} /* end if VALID_IDX(idx) */

	/* Put statements here #_TEFB_# */

	return cAPI_connect(&myaddr, myport, &dstaddr, dstport, 4, tmout );;
}

/* #[<ENTRY_FUNC>]# eAPI4_send
 * name:         eAPI4_send
 * global_name:  tTCPCEPwrapper4_eAPI4_send
 * oneway:       false
 * #[</ENTRY_FUNC>]# */
ER_UINT
eAPI4_send(CELLIDX idx, const int8_t* data, int32_t len, TMO tmout)
{
	ER		ercd = E_OK;
	CELLCB	*p_cellcb;
	if (VALID_IDX(idx)) {
		p_cellcb = GET_CELLCB(idx);
	}
	else {
		return(E_ID);
	} /* end if VALID_IDX(idx) */

	/* Put statements here #_TEFB_# */

	return cAPI_send( data, len, tmout );;
}

/* #[<ENTRY_FUNC>]# eAPI4_receive
 * name:         eAPI4_receive
 * global_name:  tTCPCEPwrapper4_eAPI4_receive
 * oneway:       false
 * #[</ENTRY_FUNC>]# */
ER_UINT
eAPI4_receive(CELLIDX idx, int8_t* data, int32_t len, TMO tmout)
{
	ER		ercd = E_OK;
	CELLCB	*p_cellcb;
	if (VALID_IDX(idx)) {
		p_cellcb = GET_CELLCB(idx);
	}
	else {
		return(E_ID);
	} /* end if VALID_IDX(idx) */

	/* Put statements here #_TEFB_# */

	return cAPI_receive(data,len, tmout );;
}

/* #[<ENTRY_FUNC>]# eAPI4_cancel
 * name:         eAPI4_cancel
 * global_name:  tTCPCEPwrapper4_eAPI4_cancel
 * oneway:       false
 * #[</ENTRY_FUNC>]# */
ER
eAPI4_cancel(CELLIDX idx, FN fncd)
{
	ER		ercd = E_OK;
	CELLCB	*p_cellcb;
	if (VALID_IDX(idx)) {
		p_cellcb = GET_CELLCB(idx);
	}
	else {
		return(E_ID);
	} /* end if VALID_IDX(idx) */

	/* Put statements here #_TEFB_# */

	return cAPI_cancel(fncd);
}

/* #[<ENTRY_FUNC>]# eAPI4_close
 * name:         eAPI4_close
 * global_name:  tTCPCEPwrapper4_eAPI4_close
 * oneway:       false
 * #[</ENTRY_FUNC>]# */
ER
eAPI4_close(CELLIDX idx, TMO tmout)
{
	ER		ercd = E_OK;
	CELLCB	*p_cellcb;
	if (VALID_IDX(idx)) {
		p_cellcb = GET_CELLCB(idx);
	}
	else {
		return(E_ID);
	} /* end if VALID_IDX(idx) */

	/* Put statements here #_TEFB_# */

	return cAPI_close(tmout);
}

/* #[<ENTRY_FUNC>]# eAPI4_shutdown
 * name:         eAPI4_shutdown
 * global_name:  tTCPCEPwrapper4_eAPI4_shutdown
 * oneway:       false
 * #[</ENTRY_FUNC>]# */
ER
eAPI4_shutdown(CELLIDX idx)
{
	ER		ercd = E_OK;
	CELLCB	*p_cellcb;
	if (VALID_IDX(idx)) {
		p_cellcb = GET_CELLCB(idx);
	}
	else {
		return(E_ID);
	} /* end if VALID_IDX(idx) */

	/* Put statements here #_TEFB_# */

	return cAPI_shutdown();
}

/* #[<ENTRY_PORT>]# eGetAddress4
 * entry port: eGetAddress4
 * signature:  sGetAddress2
 * context:    task
 * #[</ENTRY_PORT>]# */

/* #[<ENTRY_FUNC>]# eGetAddress4_getMyAddress
 * name:         eGetAddress4_getMyAddress
 * global_name:  tTCPCEPwrapper4_eGetAddress4_getMyAddress
 * oneway:       false
 * #[</ENTRY_FUNC>]# */
int8_t*
eGetAddress4_getMyAddress(CELLIDX idx)
{
	CELLCB	*p_cellcb;
	if (VALID_IDX(idx)) {
		p_cellcb = GET_CELLCB(idx);
	}
	else {
		/* Write error processing code here */
	} /* end if VALID_IDX(idx) */

	/* Put statements here #_TEFB_# */

	return &VAR_myaddr;
}

/* #[<ENTRY_FUNC>]# eGetAddress4_getDstAddress
 * name:         eGetAddress4_getDstAddress
 * global_name:  tTCPCEPwrapper4_eGetAddress4_getDstAddress
 * oneway:       false
 * #[</ENTRY_FUNC>]# */
int8_t*
eGetAddress4_getDstAddress(CELLIDX idx)
{
	CELLCB	*p_cellcb;
	if (VALID_IDX(idx)) {
		p_cellcb = GET_CELLCB(idx);
	}
	else {
		/* Write error processing code here */
	} /* end if VALID_IDX(idx) */

	/* Put statements here #_TEFB_# */

	return &VAR_dstaddr;
}

/* #[<ENTRY_FUNC>]# eGetAddress4_setMy4Address
 * name:         eGetAddress4_setMy4Address
 * global_name:  tTCPCEPwrapper4_eGetAddress4_setMy4Address
 * oneway:       false
 * #[</ENTRY_FUNC>]# */
void
eGetAddress4_setMy4Address(CELLIDX idx, T_IN4_ADDR addr)
{
	CELLCB	*p_cellcb;
	if (VALID_IDX(idx)) {
		p_cellcb = GET_CELLCB(idx);
	}
	else {
		/* Write error processing code here */
	} /* end if VALID_IDX(idx) */

	/* Put statements here #_TEFB_# */
	VAR_myaddr = addr;

}

/* #[<ENTRY_FUNC>]# eGetAddress4_setDst4Address
 * name:         eGetAddress4_setDst4Address
 * global_name:  tTCPCEPwrapper4_eGetAddress4_setDst4Address
 * oneway:       false
 * #[</ENTRY_FUNC>]# */
void
eGetAddress4_setDst4Address(CELLIDX idx, T_IN4_ADDR addr)
{
	CELLCB	*p_cellcb;
	if (VALID_IDX(idx)) {
		p_cellcb = GET_CELLCB(idx);
	}
	else {
		/* Write error processing code here */
	} /* end if VALID_IDX(idx) */

	/* Put statements here #_TEFB_# */
	VAR_dstaddr = addr;
}

/* #[<POSTAMBLE>]#
 *   Put non-entry functions below.
 * #[</POSTAMBLE>]#*/
